spring:
  application:
    name: taco-kitchen
  kafka:
    bootstrap-servers:
    - localhost:9092
    template:
      default-topic: tacoworld-orders.topic
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: tacoworld_kitchen
      properties:
        spring.json.trusted.packages: org.mhacioglu.*
server:
  port: 8085
